### ISSUE TITLE
Moodle 3.1 / PHP7

### ISSUE THREAD

**Issue by euneuber** [moodleou/moodle-qtype_combined#3]
Hi, starting a new quiz attempt leads to an empty page. Error message says:
```
Fatal error: Cannot declare class qtype_combined_combinable_type_gapselect, 
because the name is already in use in 
/srv/www/vhosts/moodle/question/type/combined/combinable/gapselect/combinable.php 
on line 56
```
Putting (in file combinable/gapselect/combinable.php )
```
if (!class_exists('qtype_combined_combinable_type_gapselect')) {
    class qtype_combined_combinable_type_gapselect extends qtype_combined_combinable_type_base {
    ...
   }
}
```
fixed it.

**Comment by timhunt** [comment]
Acutally, the problem is that when you upgraded your Moodle site, you did not correctly upgrade the Moodle code.

A common mistake is to copy the new code on top of the old code. This does not remove files that have been removed from the codebase between releases.

If you are running Moodle 3.1, the directory question/type/gapselect/combinable should not exist. https://github.com/moodle/moodle/tree/MOODLE_31_STABLE/question/type/gapselect
